//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirServicioWeb.CadenaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Clientes", Namespace="http://schemas.datacontract.org/2004/07/Cedesistemas.Model.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class Clientes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Movimientos> MovimientosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Movimientos> Movimientos {
            get {
                return this.MovimientosField;
            }
            set {
                if ((object.ReferenceEquals(this.MovimientosField, value) != true)) {
                    this.MovimientosField = value;
                    this.RaisePropertyChanged("Movimientos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movimientos", Namespace="http://schemas.datacontract.org/2004/07/Cedesistemas.Model.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class Movimientos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgenciaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumirServicioWeb.CadenaService.Agencias AgenciasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaseVueloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumirServicioWeb.CadenaService.Clientes ClientesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaLlegadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaSalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MovimientoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreAgenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ServicioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumirServicioWeb.CadenaService.Servicios ServiciosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VueloIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumirServicioWeb.CadenaService.Vuelos VuelosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgenciaId {
            get {
                return this.AgenciaIdField;
            }
            set {
                if ((this.AgenciaIdField.Equals(value) != true)) {
                    this.AgenciaIdField = value;
                    this.RaisePropertyChanged("AgenciaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsumirServicioWeb.CadenaService.Agencias Agencias {
            get {
                return this.AgenciasField;
            }
            set {
                if ((object.ReferenceEquals(this.AgenciasField, value) != true)) {
                    this.AgenciasField = value;
                    this.RaisePropertyChanged("Agencias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaseVuelo {
            get {
                return this.ClaseVueloField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaseVueloField, value) != true)) {
                    this.ClaseVueloField = value;
                    this.RaisePropertyChanged("ClaseVuelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsumirServicioWeb.CadenaService.Clientes Clientes {
            get {
                return this.ClientesField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientesField, value) != true)) {
                    this.ClientesField = value;
                    this.RaisePropertyChanged("Clientes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoReserva {
            get {
                return this.CodigoReservaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoReservaField, value) != true)) {
                    this.CodigoReservaField = value;
                    this.RaisePropertyChanged("CodigoReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaLlegada {
            get {
                return this.FechaLlegadaField;
            }
            set {
                if ((this.FechaLlegadaField.Equals(value) != true)) {
                    this.FechaLlegadaField = value;
                    this.RaisePropertyChanged("FechaLlegada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaSalida {
            get {
                return this.FechaSalidaField;
            }
            set {
                if ((this.FechaSalidaField.Equals(value) != true)) {
                    this.FechaSalidaField = value;
                    this.RaisePropertyChanged("FechaSalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MovimientoId {
            get {
                return this.MovimientoIdField;
            }
            set {
                if ((this.MovimientoIdField.Equals(value) != true)) {
                    this.MovimientoIdField = value;
                    this.RaisePropertyChanged("MovimientoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreAgencia {
            get {
                return this.NombreAgenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreAgenciaField, value) != true)) {
                    this.NombreAgenciaField = value;
                    this.RaisePropertyChanged("NombreAgencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ServicioId {
            get {
                return this.ServicioIdField;
            }
            set {
                if ((this.ServicioIdField.Equals(value) != true)) {
                    this.ServicioIdField = value;
                    this.RaisePropertyChanged("ServicioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsumirServicioWeb.CadenaService.Servicios Servicios {
            get {
                return this.ServiciosField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiciosField, value) != true)) {
                    this.ServiciosField = value;
                    this.RaisePropertyChanged("Servicios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> VueloId {
            get {
                return this.VueloIdField;
            }
            set {
                if ((this.VueloIdField.Equals(value) != true)) {
                    this.VueloIdField = value;
                    this.RaisePropertyChanged("VueloId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsumirServicioWeb.CadenaService.Vuelos Vuelos {
            get {
                return this.VuelosField;
            }
            set {
                if ((object.ReferenceEquals(this.VuelosField, value) != true)) {
                    this.VuelosField = value;
                    this.RaisePropertyChanged("Vuelos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Agencias", Namespace="http://schemas.datacontract.org/2004/07/Cedesistemas.Model.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class Agencias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgenciaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CadenaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumirServicioWeb.CadenaService.Cadenas CadenasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Movimientos> MovimientosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgenciaId {
            get {
                return this.AgenciaIdField;
            }
            set {
                if ((this.AgenciaIdField.Equals(value) != true)) {
                    this.AgenciaIdField = value;
                    this.RaisePropertyChanged("AgenciaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CadenaId {
            get {
                return this.CadenaIdField;
            }
            set {
                if ((this.CadenaIdField.Equals(value) != true)) {
                    this.CadenaIdField = value;
                    this.RaisePropertyChanged("CadenaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsumirServicioWeb.CadenaService.Cadenas Cadenas {
            get {
                return this.CadenasField;
            }
            set {
                if ((object.ReferenceEquals(this.CadenasField, value) != true)) {
                    this.CadenasField = value;
                    this.RaisePropertyChanged("Cadenas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Movimientos> Movimientos {
            get {
                return this.MovimientosField;
            }
            set {
                if ((object.ReferenceEquals(this.MovimientosField, value) != true)) {
                    this.MovimientosField = value;
                    this.RaisePropertyChanged("Movimientos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Servicios", Namespace="http://schemas.datacontract.org/2004/07/Cedesistemas.Model.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class Servicios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DescuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HotelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumirServicioWeb.CadenaService.Hoteles HotelesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Movimientos> MovimientosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ServicioIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Descuento {
            get {
                return this.DescuentoField;
            }
            set {
                if ((this.DescuentoField.Equals(value) != true)) {
                    this.DescuentoField = value;
                    this.RaisePropertyChanged("Descuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HotelId {
            get {
                return this.HotelIdField;
            }
            set {
                if ((this.HotelIdField.Equals(value) != true)) {
                    this.HotelIdField = value;
                    this.RaisePropertyChanged("HotelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsumirServicioWeb.CadenaService.Hoteles Hoteles {
            get {
                return this.HotelesField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelesField, value) != true)) {
                    this.HotelesField = value;
                    this.RaisePropertyChanged("Hoteles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Movimientos> Movimientos {
            get {
                return this.MovimientosField;
            }
            set {
                if ((object.ReferenceEquals(this.MovimientosField, value) != true)) {
                    this.MovimientosField = value;
                    this.RaisePropertyChanged("Movimientos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServicioId {
            get {
                return this.ServicioIdField;
            }
            set {
                if ((this.ServicioIdField.Equals(value) != true)) {
                    this.ServicioIdField = value;
                    this.RaisePropertyChanged("ServicioId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vuelos", Namespace="http://schemas.datacontract.org/2004/07/Cedesistemas.Model.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class Vuelos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CadenaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumirServicioWeb.CadenaService.Cadenas CadenasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CiudadIdDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CiudadIdOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumirServicioWeb.CadenaService.Ciudades CiudadesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumirServicioWeb.CadenaService.Ciudades Ciudades1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaVueloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan HoraVueloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Movimientos> MovimientosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumeroPlazaEjecutivaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumeroPlazaTuristaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VueloIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CadenaId {
            get {
                return this.CadenaIdField;
            }
            set {
                if ((this.CadenaIdField.Equals(value) != true)) {
                    this.CadenaIdField = value;
                    this.RaisePropertyChanged("CadenaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsumirServicioWeb.CadenaService.Cadenas Cadenas {
            get {
                return this.CadenasField;
            }
            set {
                if ((object.ReferenceEquals(this.CadenasField, value) != true)) {
                    this.CadenasField = value;
                    this.RaisePropertyChanged("Cadenas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CiudadIdDestino {
            get {
                return this.CiudadIdDestinoField;
            }
            set {
                if ((this.CiudadIdDestinoField.Equals(value) != true)) {
                    this.CiudadIdDestinoField = value;
                    this.RaisePropertyChanged("CiudadIdDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CiudadIdOrigen {
            get {
                return this.CiudadIdOrigenField;
            }
            set {
                if ((this.CiudadIdOrigenField.Equals(value) != true)) {
                    this.CiudadIdOrigenField = value;
                    this.RaisePropertyChanged("CiudadIdOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsumirServicioWeb.CadenaService.Ciudades Ciudades {
            get {
                return this.CiudadesField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadesField, value) != true)) {
                    this.CiudadesField = value;
                    this.RaisePropertyChanged("Ciudades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsumirServicioWeb.CadenaService.Ciudades Ciudades1 {
            get {
                return this.Ciudades1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Ciudades1Field, value) != true)) {
                    this.Ciudades1Field = value;
                    this.RaisePropertyChanged("Ciudades1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaVuelo {
            get {
                return this.FechaVueloField;
            }
            set {
                if ((this.FechaVueloField.Equals(value) != true)) {
                    this.FechaVueloField = value;
                    this.RaisePropertyChanged("FechaVuelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan HoraVuelo {
            get {
                return this.HoraVueloField;
            }
            set {
                if ((this.HoraVueloField.Equals(value) != true)) {
                    this.HoraVueloField = value;
                    this.RaisePropertyChanged("HoraVuelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Movimientos> Movimientos {
            get {
                return this.MovimientosField;
            }
            set {
                if ((object.ReferenceEquals(this.MovimientosField, value) != true)) {
                    this.MovimientosField = value;
                    this.RaisePropertyChanged("Movimientos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumeroPlazaEjecutiva {
            get {
                return this.NumeroPlazaEjecutivaField;
            }
            set {
                if ((this.NumeroPlazaEjecutivaField.Equals(value) != true)) {
                    this.NumeroPlazaEjecutivaField = value;
                    this.RaisePropertyChanged("NumeroPlazaEjecutiva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumeroPlazaTurista {
            get {
                return this.NumeroPlazaTuristaField;
            }
            set {
                if ((this.NumeroPlazaTuristaField.Equals(value) != true)) {
                    this.NumeroPlazaTuristaField = value;
                    this.RaisePropertyChanged("NumeroPlazaTurista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VueloId {
            get {
                return this.VueloIdField;
            }
            set {
                if ((this.VueloIdField.Equals(value) != true)) {
                    this.VueloIdField = value;
                    this.RaisePropertyChanged("VueloId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cadenas", Namespace="http://schemas.datacontract.org/2004/07/Cedesistemas.Model.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class Cadenas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Agencias> AgenciasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CadenaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Hoteles> HotelesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Vuelos> VuelosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Agencias> Agencias {
            get {
                return this.AgenciasField;
            }
            set {
                if ((object.ReferenceEquals(this.AgenciasField, value) != true)) {
                    this.AgenciasField = value;
                    this.RaisePropertyChanged("Agencias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CadenaId {
            get {
                return this.CadenaIdField;
            }
            set {
                if ((this.CadenaIdField.Equals(value) != true)) {
                    this.CadenaIdField = value;
                    this.RaisePropertyChanged("CadenaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Hoteles> Hoteles {
            get {
                return this.HotelesField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelesField, value) != true)) {
                    this.HotelesField = value;
                    this.RaisePropertyChanged("Hoteles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Vuelos> Vuelos {
            get {
                return this.VuelosField;
            }
            set {
                if ((object.ReferenceEquals(this.VuelosField, value) != true)) {
                    this.VuelosField = value;
                    this.RaisePropertyChanged("Vuelos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hoteles", Namespace="http://schemas.datacontract.org/2004/07/Cedesistemas.Model.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class Hoteles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CadenaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumirServicioWeb.CadenaService.Cadenas CadenasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CiudadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumirServicioWeb.CadenaService.Ciudades CiudadesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HotelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumeroPlazasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Servicios> ServiciosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CadenaId {
            get {
                return this.CadenaIdField;
            }
            set {
                if ((this.CadenaIdField.Equals(value) != true)) {
                    this.CadenaIdField = value;
                    this.RaisePropertyChanged("CadenaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsumirServicioWeb.CadenaService.Cadenas Cadenas {
            get {
                return this.CadenasField;
            }
            set {
                if ((object.ReferenceEquals(this.CadenasField, value) != true)) {
                    this.CadenasField = value;
                    this.RaisePropertyChanged("Cadenas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CiudadId {
            get {
                return this.CiudadIdField;
            }
            set {
                if ((this.CiudadIdField.Equals(value) != true)) {
                    this.CiudadIdField = value;
                    this.RaisePropertyChanged("CiudadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsumirServicioWeb.CadenaService.Ciudades Ciudades {
            get {
                return this.CiudadesField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadesField, value) != true)) {
                    this.CiudadesField = value;
                    this.RaisePropertyChanged("Ciudades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HotelId {
            get {
                return this.HotelIdField;
            }
            set {
                if ((this.HotelIdField.Equals(value) != true)) {
                    this.HotelIdField = value;
                    this.RaisePropertyChanged("HotelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumeroPlazas {
            get {
                return this.NumeroPlazasField;
            }
            set {
                if ((this.NumeroPlazasField.Equals(value) != true)) {
                    this.NumeroPlazasField = value;
                    this.RaisePropertyChanged("NumeroPlazas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Servicios> Servicios {
            get {
                return this.ServiciosField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiciosField, value) != true)) {
                    this.ServiciosField = value;
                    this.RaisePropertyChanged("Servicios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ciudades", Namespace="http://schemas.datacontract.org/2004/07/Cedesistemas.Model.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class Ciudades : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CiudadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DepartamentoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumirServicioWeb.CadenaService.Departamentos DepartamentosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Hoteles> HotelesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Vuelos> VuelosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Vuelos> Vuelos1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CiudadId {
            get {
                return this.CiudadIdField;
            }
            set {
                if ((this.CiudadIdField.Equals(value) != true)) {
                    this.CiudadIdField = value;
                    this.RaisePropertyChanged("CiudadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DepartamentoId {
            get {
                return this.DepartamentoIdField;
            }
            set {
                if ((this.DepartamentoIdField.Equals(value) != true)) {
                    this.DepartamentoIdField = value;
                    this.RaisePropertyChanged("DepartamentoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsumirServicioWeb.CadenaService.Departamentos Departamentos {
            get {
                return this.DepartamentosField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentosField, value) != true)) {
                    this.DepartamentosField = value;
                    this.RaisePropertyChanged("Departamentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Hoteles> Hoteles {
            get {
                return this.HotelesField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelesField, value) != true)) {
                    this.HotelesField = value;
                    this.RaisePropertyChanged("Hoteles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Vuelos> Vuelos {
            get {
                return this.VuelosField;
            }
            set {
                if ((object.ReferenceEquals(this.VuelosField, value) != true)) {
                    this.VuelosField = value;
                    this.RaisePropertyChanged("Vuelos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Vuelos> Vuelos1 {
            get {
                return this.Vuelos1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Vuelos1Field, value) != true)) {
                    this.Vuelos1Field = value;
                    this.RaisePropertyChanged("Vuelos1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Departamentos", Namespace="http://schemas.datacontract.org/2004/07/Cedesistemas.Model.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class Departamentos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Ciudades> CiudadesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartamentoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Ciudades> Ciudades {
            get {
                return this.CiudadesField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadesField, value) != true)) {
                    this.CiudadesField = value;
                    this.RaisePropertyChanged("Ciudades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartamentoId {
            get {
                return this.DepartamentoIdField;
            }
            set {
                if ((this.DepartamentoIdField.Equals(value) != true)) {
                    this.DepartamentoIdField = value;
                    this.RaisePropertyChanged("DepartamentoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CadenaService.IAgenciasViajesApi")]
    public interface IAgenciasViajesApi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenciasViajesApi/SelectAllClientes", ReplyAction="http://tempuri.org/IAgenciasViajesApi/SelectAllClientesResponse")]
        System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Clientes> SelectAllClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenciasViajesApi/SelectAllClientes", ReplyAction="http://tempuri.org/IAgenciasViajesApi/SelectAllClientesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Clientes>> SelectAllClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenciasViajesApi/SelectClienteById", ReplyAction="http://tempuri.org/IAgenciasViajesApi/SelectClienteByIdResponse")]
        ConsumirServicioWeb.CadenaService.Clientes SelectClienteById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenciasViajesApi/SelectClienteById", ReplyAction="http://tempuri.org/IAgenciasViajesApi/SelectClienteByIdResponse")]
        System.Threading.Tasks.Task<ConsumirServicioWeb.CadenaService.Clientes> SelectClienteByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAgenciasViajesApiChannel : ConsumirServicioWeb.CadenaService.IAgenciasViajesApi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgenciasViajesApiClient : System.ServiceModel.ClientBase<ConsumirServicioWeb.CadenaService.IAgenciasViajesApi>, ConsumirServicioWeb.CadenaService.IAgenciasViajesApi {
        
        public AgenciasViajesApiClient() {
        }
        
        public AgenciasViajesApiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgenciasViajesApiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgenciasViajesApiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgenciasViajesApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Clientes> SelectAllClientes() {
            return base.Channel.SelectAllClientes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConsumirServicioWeb.CadenaService.Clientes>> SelectAllClientesAsync() {
            return base.Channel.SelectAllClientesAsync();
        }
        
        public ConsumirServicioWeb.CadenaService.Clientes SelectClienteById(int id) {
            return base.Channel.SelectClienteById(id);
        }
        
        public System.Threading.Tasks.Task<ConsumirServicioWeb.CadenaService.Clientes> SelectClienteByIdAsync(int id) {
            return base.Channel.SelectClienteByIdAsync(id);
        }
    }
}
