//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirServicioWeb.EjemploWcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonaDto", Namespace="http://schemas.datacontract.org/2004/07/EjemploServicios.Dto")]
    [System.SerializableAttribute()]
    public partial class PersonaDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EjemploWcf.IEjemploWcf")]
    public interface IEjemploWcf {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEjemploWcf/DoWork", ReplyAction="http://tempuri.org/IEjemploWcf/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEjemploWcf/DoWork", ReplyAction="http://tempuri.org/IEjemploWcf/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEjemploWcf/CalcularDato", ReplyAction="http://tempuri.org/IEjemploWcf/CalcularDatoResponse")]
        int CalcularDato(int valor1, int valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEjemploWcf/CalcularDato", ReplyAction="http://tempuri.org/IEjemploWcf/CalcularDatoResponse")]
        System.Threading.Tasks.Task<int> CalcularDatoAsync(int valor1, int valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEjemploWcf/SelectAllPersonas", ReplyAction="http://tempuri.org/IEjemploWcf/SelectAllPersonasResponse")]
        System.Collections.Generic.List<ConsumirServicioWeb.EjemploWcf.PersonaDto> SelectAllPersonas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEjemploWcf/SelectAllPersonas", ReplyAction="http://tempuri.org/IEjemploWcf/SelectAllPersonasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConsumirServicioWeb.EjemploWcf.PersonaDto>> SelectAllPersonasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEjemploWcfChannel : ConsumirServicioWeb.EjemploWcf.IEjemploWcf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EjemploWcfClient : System.ServiceModel.ClientBase<ConsumirServicioWeb.EjemploWcf.IEjemploWcf>, ConsumirServicioWeb.EjemploWcf.IEjemploWcf {
        
        public EjemploWcfClient() {
        }
        
        public EjemploWcfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EjemploWcfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EjemploWcfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EjemploWcfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public int CalcularDato(int valor1, int valor2) {
            return base.Channel.CalcularDato(valor1, valor2);
        }
        
        public System.Threading.Tasks.Task<int> CalcularDatoAsync(int valor1, int valor2) {
            return base.Channel.CalcularDatoAsync(valor1, valor2);
        }
        
        public System.Collections.Generic.List<ConsumirServicioWeb.EjemploWcf.PersonaDto> SelectAllPersonas() {
            return base.Channel.SelectAllPersonas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConsumirServicioWeb.EjemploWcf.PersonaDto>> SelectAllPersonasAsync() {
            return base.Channel.SelectAllPersonasAsync();
        }
    }
}
