//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploConsumoConsola.ServiceEsteban {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEsteban.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name cuponCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoNombrePropietarioCupon", ReplyAction="*")]
        EjemploConsumoConsola.ServiceEsteban.GetInfoNombrePropietarioCuponResponse GetInfoNombrePropietarioCupon(EjemploConsumoConsola.ServiceEsteban.GetInfoNombrePropietarioCuponRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoNombrePropietarioCupon", ReplyAction="*")]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetInfoNombrePropietarioCuponResponse> GetInfoNombrePropietarioCuponAsync(EjemploConsumoConsola.ServiceEsteban.GetInfoNombrePropietarioCuponRequest request);
        
        // CODEGEN: Generating message contract since element name cuponCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoCedulaPropietarioCupon", ReplyAction="*")]
        EjemploConsumoConsola.ServiceEsteban.GetInfoCedulaPropietarioCuponResponse GetInfoCedulaPropietarioCupon(EjemploConsumoConsola.ServiceEsteban.GetInfoCedulaPropietarioCuponRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoCedulaPropietarioCupon", ReplyAction="*")]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetInfoCedulaPropietarioCuponResponse> GetInfoCedulaPropietarioCuponAsync(EjemploConsumoConsola.ServiceEsteban.GetInfoCedulaPropietarioCuponRequest request);
        
        // CODEGEN: Generating message contract since element name cuponCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoCuponActivo", ReplyAction="*")]
        EjemploConsumoConsola.ServiceEsteban.GetInfoCuponActivoResponse GetInfoCuponActivo(EjemploConsumoConsola.ServiceEsteban.GetInfoCuponActivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoCuponActivo", ReplyAction="*")]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetInfoCuponActivoResponse> GetInfoCuponActivoAsync(EjemploConsumoConsola.ServiceEsteban.GetInfoCuponActivoRequest request);
        
        // CODEGEN: Generating message contract since element name cuponCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoFechaCaducidadCupon", ReplyAction="*")]
        EjemploConsumoConsola.ServiceEsteban.GetInfoFechaCaducidadCuponResponse GetInfoFechaCaducidadCupon(EjemploConsumoConsola.ServiceEsteban.GetInfoFechaCaducidadCuponRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoFechaCaducidadCupon", ReplyAction="*")]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetInfoFechaCaducidadCuponResponse> GetInfoFechaCaducidadCuponAsync(EjemploConsumoConsola.ServiceEsteban.GetInfoFechaCaducidadCuponRequest request);
        
        // CODEGEN: Generating message contract since element name cuponCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoNroAplicadoCupon", ReplyAction="*")]
        EjemploConsumoConsola.ServiceEsteban.GetInfoNroAplicadoCuponResponse GetInfoNroAplicadoCupon(EjemploConsumoConsola.ServiceEsteban.GetInfoNroAplicadoCuponRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoNroAplicadoCupon", ReplyAction="*")]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetInfoNroAplicadoCuponResponse> GetInfoNroAplicadoCuponAsync(EjemploConsumoConsola.ServiceEsteban.GetInfoNroAplicadoCuponRequest request);
        
        // CODEGEN: Generating message contract since element name cuponCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoCodPromoCupon", ReplyAction="*")]
        EjemploConsumoConsola.ServiceEsteban.GetInfoCodPromoCuponResponse GetInfoCodPromoCupon(EjemploConsumoConsola.ServiceEsteban.GetInfoCodPromoCuponRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoCodPromoCupon", ReplyAction="*")]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetInfoCodPromoCuponResponse> GetInfoCodPromoCuponAsync(EjemploConsumoConsola.ServiceEsteban.GetInfoCodPromoCuponRequest request);
        
        // CODEGEN: Generating message contract since element name cuponCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoTipoPromoCupon", ReplyAction="*")]
        EjemploConsumoConsola.ServiceEsteban.GetInfoTipoPromoCuponResponse GetInfoTipoPromoCupon(EjemploConsumoConsola.ServiceEsteban.GetInfoTipoPromoCuponRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoTipoPromoCupon", ReplyAction="*")]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetInfoTipoPromoCuponResponse> GetInfoTipoPromoCuponAsync(EjemploConsumoConsola.ServiceEsteban.GetInfoTipoPromoCuponRequest request);
        
        // CODEGEN: Generating message contract since element name codPromocion from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTipoPromocionCamposlibres", ReplyAction="*")]
        EjemploConsumoConsola.ServiceEsteban.GetTipoPromocionCamposlibresResponse GetTipoPromocionCamposlibres(EjemploConsumoConsola.ServiceEsteban.GetTipoPromocionCamposlibresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTipoPromocionCamposlibres", ReplyAction="*")]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetTipoPromocionCamposlibresResponse> GetTipoPromocionCamposlibresAsync(EjemploConsumoConsola.ServiceEsteban.GetTipoPromocionCamposlibresRequest request);
        
        // CODEGEN: Generating message contract since element name cuponCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCodArticuloPromo", ReplyAction="*")]
        EjemploConsumoConsola.ServiceEsteban.GetCodArticuloPromoResponse GetCodArticuloPromo(EjemploConsumoConsola.ServiceEsteban.GetCodArticuloPromoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCodArticuloPromo", ReplyAction="*")]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetCodArticuloPromoResponse> GetCodArticuloPromoAsync(EjemploConsumoConsola.ServiceEsteban.GetCodArticuloPromoRequest request);
        
        // CODEGEN: Generating message contract since element name cuponCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUnidadesRegaloPromo", ReplyAction="*")]
        EjemploConsumoConsola.ServiceEsteban.GetUnidadesRegaloPromoResponse GetUnidadesRegaloPromo(EjemploConsumoConsola.ServiceEsteban.GetUnidadesRegaloPromoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUnidadesRegaloPromo", ReplyAction="*")]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetUnidadesRegaloPromoResponse> GetUnidadesRegaloPromoAsync(EjemploConsumoConsola.ServiceEsteban.GetUnidadesRegaloPromoRequest request);
        
        // CODEGEN: Generating message contract since element name cuponCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDescuentoPromo", ReplyAction="*")]
        EjemploConsumoConsola.ServiceEsteban.GetDescuentoPromoResponse GetDescuentoPromo(EjemploConsumoConsola.ServiceEsteban.GetDescuentoPromoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDescuentoPromo", ReplyAction="*")]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetDescuentoPromoResponse> GetDescuentoPromoAsync(EjemploConsumoConsola.ServiceEsteban.GetDescuentoPromoRequest request);
        
        // CODEGEN: Generating message contract since element name cuponCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDesImportePromo", ReplyAction="*")]
        EjemploConsumoConsola.ServiceEsteban.GetDesImportePromoResponse GetDesImportePromo(EjemploConsumoConsola.ServiceEsteban.GetDesImportePromoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDesImportePromo", ReplyAction="*")]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetDesImportePromoResponse> GetDesImportePromoAsync(EjemploConsumoConsola.ServiceEsteban.GetDesImportePromoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoNombrePropietarioCuponRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoNombrePropietarioCupon", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetInfoNombrePropietarioCuponRequestBody Body;
        
        public GetInfoNombrePropietarioCuponRequest() {
        }
        
        public GetInfoNombrePropietarioCuponRequest(EjemploConsumoConsola.ServiceEsteban.GetInfoNombrePropietarioCuponRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoNombrePropietarioCuponRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuponCode;
        
        public GetInfoNombrePropietarioCuponRequestBody() {
        }
        
        public GetInfoNombrePropietarioCuponRequestBody(string cuponCode) {
            this.cuponCode = cuponCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoNombrePropietarioCuponResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoNombrePropietarioCuponResponse", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetInfoNombrePropietarioCuponResponseBody Body;
        
        public GetInfoNombrePropietarioCuponResponse() {
        }
        
        public GetInfoNombrePropietarioCuponResponse(EjemploConsumoConsola.ServiceEsteban.GetInfoNombrePropietarioCuponResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoNombrePropietarioCuponResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInfoNombrePropietarioCuponResult;
        
        public GetInfoNombrePropietarioCuponResponseBody() {
        }
        
        public GetInfoNombrePropietarioCuponResponseBody(string GetInfoNombrePropietarioCuponResult) {
            this.GetInfoNombrePropietarioCuponResult = GetInfoNombrePropietarioCuponResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoCedulaPropietarioCuponRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoCedulaPropietarioCupon", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetInfoCedulaPropietarioCuponRequestBody Body;
        
        public GetInfoCedulaPropietarioCuponRequest() {
        }
        
        public GetInfoCedulaPropietarioCuponRequest(EjemploConsumoConsola.ServiceEsteban.GetInfoCedulaPropietarioCuponRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoCedulaPropietarioCuponRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuponCode;
        
        public GetInfoCedulaPropietarioCuponRequestBody() {
        }
        
        public GetInfoCedulaPropietarioCuponRequestBody(string cuponCode) {
            this.cuponCode = cuponCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoCedulaPropietarioCuponResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoCedulaPropietarioCuponResponse", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetInfoCedulaPropietarioCuponResponseBody Body;
        
        public GetInfoCedulaPropietarioCuponResponse() {
        }
        
        public GetInfoCedulaPropietarioCuponResponse(EjemploConsumoConsola.ServiceEsteban.GetInfoCedulaPropietarioCuponResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoCedulaPropietarioCuponResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInfoCedulaPropietarioCuponResult;
        
        public GetInfoCedulaPropietarioCuponResponseBody() {
        }
        
        public GetInfoCedulaPropietarioCuponResponseBody(string GetInfoCedulaPropietarioCuponResult) {
            this.GetInfoCedulaPropietarioCuponResult = GetInfoCedulaPropietarioCuponResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoCuponActivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoCuponActivo", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetInfoCuponActivoRequestBody Body;
        
        public GetInfoCuponActivoRequest() {
        }
        
        public GetInfoCuponActivoRequest(EjemploConsumoConsola.ServiceEsteban.GetInfoCuponActivoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoCuponActivoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuponCode;
        
        public GetInfoCuponActivoRequestBody() {
        }
        
        public GetInfoCuponActivoRequestBody(string cuponCode) {
            this.cuponCode = cuponCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoCuponActivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoCuponActivoResponse", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetInfoCuponActivoResponseBody Body;
        
        public GetInfoCuponActivoResponse() {
        }
        
        public GetInfoCuponActivoResponse(EjemploConsumoConsola.ServiceEsteban.GetInfoCuponActivoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoCuponActivoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInfoCuponActivoResult;
        
        public GetInfoCuponActivoResponseBody() {
        }
        
        public GetInfoCuponActivoResponseBody(string GetInfoCuponActivoResult) {
            this.GetInfoCuponActivoResult = GetInfoCuponActivoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoFechaCaducidadCuponRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoFechaCaducidadCupon", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetInfoFechaCaducidadCuponRequestBody Body;
        
        public GetInfoFechaCaducidadCuponRequest() {
        }
        
        public GetInfoFechaCaducidadCuponRequest(EjemploConsumoConsola.ServiceEsteban.GetInfoFechaCaducidadCuponRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoFechaCaducidadCuponRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuponCode;
        
        public GetInfoFechaCaducidadCuponRequestBody() {
        }
        
        public GetInfoFechaCaducidadCuponRequestBody(string cuponCode) {
            this.cuponCode = cuponCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoFechaCaducidadCuponResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoFechaCaducidadCuponResponse", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetInfoFechaCaducidadCuponResponseBody Body;
        
        public GetInfoFechaCaducidadCuponResponse() {
        }
        
        public GetInfoFechaCaducidadCuponResponse(EjemploConsumoConsola.ServiceEsteban.GetInfoFechaCaducidadCuponResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoFechaCaducidadCuponResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInfoFechaCaducidadCuponResult;
        
        public GetInfoFechaCaducidadCuponResponseBody() {
        }
        
        public GetInfoFechaCaducidadCuponResponseBody(string GetInfoFechaCaducidadCuponResult) {
            this.GetInfoFechaCaducidadCuponResult = GetInfoFechaCaducidadCuponResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoNroAplicadoCuponRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoNroAplicadoCupon", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetInfoNroAplicadoCuponRequestBody Body;
        
        public GetInfoNroAplicadoCuponRequest() {
        }
        
        public GetInfoNroAplicadoCuponRequest(EjemploConsumoConsola.ServiceEsteban.GetInfoNroAplicadoCuponRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoNroAplicadoCuponRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuponCode;
        
        public GetInfoNroAplicadoCuponRequestBody() {
        }
        
        public GetInfoNroAplicadoCuponRequestBody(string cuponCode) {
            this.cuponCode = cuponCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoNroAplicadoCuponResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoNroAplicadoCuponResponse", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetInfoNroAplicadoCuponResponseBody Body;
        
        public GetInfoNroAplicadoCuponResponse() {
        }
        
        public GetInfoNroAplicadoCuponResponse(EjemploConsumoConsola.ServiceEsteban.GetInfoNroAplicadoCuponResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoNroAplicadoCuponResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInfoNroAplicadoCuponResult;
        
        public GetInfoNroAplicadoCuponResponseBody() {
        }
        
        public GetInfoNroAplicadoCuponResponseBody(string GetInfoNroAplicadoCuponResult) {
            this.GetInfoNroAplicadoCuponResult = GetInfoNroAplicadoCuponResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoCodPromoCuponRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoCodPromoCupon", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetInfoCodPromoCuponRequestBody Body;
        
        public GetInfoCodPromoCuponRequest() {
        }
        
        public GetInfoCodPromoCuponRequest(EjemploConsumoConsola.ServiceEsteban.GetInfoCodPromoCuponRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoCodPromoCuponRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuponCode;
        
        public GetInfoCodPromoCuponRequestBody() {
        }
        
        public GetInfoCodPromoCuponRequestBody(string cuponCode) {
            this.cuponCode = cuponCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoCodPromoCuponResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoCodPromoCuponResponse", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetInfoCodPromoCuponResponseBody Body;
        
        public GetInfoCodPromoCuponResponse() {
        }
        
        public GetInfoCodPromoCuponResponse(EjemploConsumoConsola.ServiceEsteban.GetInfoCodPromoCuponResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoCodPromoCuponResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInfoCodPromoCuponResult;
        
        public GetInfoCodPromoCuponResponseBody() {
        }
        
        public GetInfoCodPromoCuponResponseBody(string GetInfoCodPromoCuponResult) {
            this.GetInfoCodPromoCuponResult = GetInfoCodPromoCuponResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoTipoPromoCuponRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoTipoPromoCupon", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetInfoTipoPromoCuponRequestBody Body;
        
        public GetInfoTipoPromoCuponRequest() {
        }
        
        public GetInfoTipoPromoCuponRequest(EjemploConsumoConsola.ServiceEsteban.GetInfoTipoPromoCuponRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoTipoPromoCuponRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuponCode;
        
        public GetInfoTipoPromoCuponRequestBody() {
        }
        
        public GetInfoTipoPromoCuponRequestBody(string cuponCode) {
            this.cuponCode = cuponCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoTipoPromoCuponResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoTipoPromoCuponResponse", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetInfoTipoPromoCuponResponseBody Body;
        
        public GetInfoTipoPromoCuponResponse() {
        }
        
        public GetInfoTipoPromoCuponResponse(EjemploConsumoConsola.ServiceEsteban.GetInfoTipoPromoCuponResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoTipoPromoCuponResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInfoTipoPromoCuponResult;
        
        public GetInfoTipoPromoCuponResponseBody() {
        }
        
        public GetInfoTipoPromoCuponResponseBody(string GetInfoTipoPromoCuponResult) {
            this.GetInfoTipoPromoCuponResult = GetInfoTipoPromoCuponResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTipoPromocionCamposlibresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTipoPromocionCamposlibres", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetTipoPromocionCamposlibresRequestBody Body;
        
        public GetTipoPromocionCamposlibresRequest() {
        }
        
        public GetTipoPromocionCamposlibresRequest(EjemploConsumoConsola.ServiceEsteban.GetTipoPromocionCamposlibresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTipoPromocionCamposlibresRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codPromocion;
        
        public GetTipoPromocionCamposlibresRequestBody() {
        }
        
        public GetTipoPromocionCamposlibresRequestBody(string codPromocion) {
            this.codPromocion = codPromocion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTipoPromocionCamposlibresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTipoPromocionCamposlibresResponse", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetTipoPromocionCamposlibresResponseBody Body;
        
        public GetTipoPromocionCamposlibresResponse() {
        }
        
        public GetTipoPromocionCamposlibresResponse(EjemploConsumoConsola.ServiceEsteban.GetTipoPromocionCamposlibresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTipoPromocionCamposlibresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTipoPromocionCamposlibresResult;
        
        public GetTipoPromocionCamposlibresResponseBody() {
        }
        
        public GetTipoPromocionCamposlibresResponseBody(string GetTipoPromocionCamposlibresResult) {
            this.GetTipoPromocionCamposlibresResult = GetTipoPromocionCamposlibresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCodArticuloPromoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCodArticuloPromo", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetCodArticuloPromoRequestBody Body;
        
        public GetCodArticuloPromoRequest() {
        }
        
        public GetCodArticuloPromoRequest(EjemploConsumoConsola.ServiceEsteban.GetCodArticuloPromoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCodArticuloPromoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuponCode;
        
        public GetCodArticuloPromoRequestBody() {
        }
        
        public GetCodArticuloPromoRequestBody(string cuponCode) {
            this.cuponCode = cuponCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCodArticuloPromoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCodArticuloPromoResponse", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetCodArticuloPromoResponseBody Body;
        
        public GetCodArticuloPromoResponse() {
        }
        
        public GetCodArticuloPromoResponse(EjemploConsumoConsola.ServiceEsteban.GetCodArticuloPromoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCodArticuloPromoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCodArticuloPromoResult;
        
        public GetCodArticuloPromoResponseBody() {
        }
        
        public GetCodArticuloPromoResponseBody(string GetCodArticuloPromoResult) {
            this.GetCodArticuloPromoResult = GetCodArticuloPromoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUnidadesRegaloPromoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUnidadesRegaloPromo", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetUnidadesRegaloPromoRequestBody Body;
        
        public GetUnidadesRegaloPromoRequest() {
        }
        
        public GetUnidadesRegaloPromoRequest(EjemploConsumoConsola.ServiceEsteban.GetUnidadesRegaloPromoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUnidadesRegaloPromoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuponCode;
        
        public GetUnidadesRegaloPromoRequestBody() {
        }
        
        public GetUnidadesRegaloPromoRequestBody(string cuponCode) {
            this.cuponCode = cuponCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUnidadesRegaloPromoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUnidadesRegaloPromoResponse", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetUnidadesRegaloPromoResponseBody Body;
        
        public GetUnidadesRegaloPromoResponse() {
        }
        
        public GetUnidadesRegaloPromoResponse(EjemploConsumoConsola.ServiceEsteban.GetUnidadesRegaloPromoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUnidadesRegaloPromoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUnidadesRegaloPromoResult;
        
        public GetUnidadesRegaloPromoResponseBody() {
        }
        
        public GetUnidadesRegaloPromoResponseBody(string GetUnidadesRegaloPromoResult) {
            this.GetUnidadesRegaloPromoResult = GetUnidadesRegaloPromoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDescuentoPromoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDescuentoPromo", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetDescuentoPromoRequestBody Body;
        
        public GetDescuentoPromoRequest() {
        }
        
        public GetDescuentoPromoRequest(EjemploConsumoConsola.ServiceEsteban.GetDescuentoPromoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDescuentoPromoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuponCode;
        
        public GetDescuentoPromoRequestBody() {
        }
        
        public GetDescuentoPromoRequestBody(string cuponCode) {
            this.cuponCode = cuponCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDescuentoPromoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDescuentoPromoResponse", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetDescuentoPromoResponseBody Body;
        
        public GetDescuentoPromoResponse() {
        }
        
        public GetDescuentoPromoResponse(EjemploConsumoConsola.ServiceEsteban.GetDescuentoPromoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDescuentoPromoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDescuentoPromoResult;
        
        public GetDescuentoPromoResponseBody() {
        }
        
        public GetDescuentoPromoResponseBody(string GetDescuentoPromoResult) {
            this.GetDescuentoPromoResult = GetDescuentoPromoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDesImportePromoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDesImportePromo", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetDesImportePromoRequestBody Body;
        
        public GetDesImportePromoRequest() {
        }
        
        public GetDesImportePromoRequest(EjemploConsumoConsola.ServiceEsteban.GetDesImportePromoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDesImportePromoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuponCode;
        
        public GetDesImportePromoRequestBody() {
        }
        
        public GetDesImportePromoRequestBody(string cuponCode) {
            this.cuponCode = cuponCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDesImportePromoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDesImportePromoResponse", Namespace="http://tempuri.org/", Order=0)]
        public EjemploConsumoConsola.ServiceEsteban.GetDesImportePromoResponseBody Body;
        
        public GetDesImportePromoResponse() {
        }
        
        public GetDesImportePromoResponse(EjemploConsumoConsola.ServiceEsteban.GetDesImportePromoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDesImportePromoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDesImportePromoResult;
        
        public GetDesImportePromoResponseBody() {
        }
        
        public GetDesImportePromoResponseBody(string GetDesImportePromoResult) {
            this.GetDesImportePromoResult = GetDesImportePromoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : EjemploConsumoConsola.ServiceEsteban.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<EjemploConsumoConsola.ServiceEsteban.Service1Soap>, EjemploConsumoConsola.ServiceEsteban.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EjemploConsumoConsola.ServiceEsteban.GetInfoNombrePropietarioCuponResponse EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetInfoNombrePropietarioCupon(EjemploConsumoConsola.ServiceEsteban.GetInfoNombrePropietarioCuponRequest request) {
            return base.Channel.GetInfoNombrePropietarioCupon(request);
        }
        
        public string GetInfoNombrePropietarioCupon(string cuponCode) {
            EjemploConsumoConsola.ServiceEsteban.GetInfoNombrePropietarioCuponRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetInfoNombrePropietarioCuponRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetInfoNombrePropietarioCuponRequestBody();
            inValue.Body.cuponCode = cuponCode;
            EjemploConsumoConsola.ServiceEsteban.GetInfoNombrePropietarioCuponResponse retVal = ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetInfoNombrePropietarioCupon(inValue);
            return retVal.Body.GetInfoNombrePropietarioCuponResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetInfoNombrePropietarioCuponResponse> EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetInfoNombrePropietarioCuponAsync(EjemploConsumoConsola.ServiceEsteban.GetInfoNombrePropietarioCuponRequest request) {
            return base.Channel.GetInfoNombrePropietarioCuponAsync(request);
        }
        
        public System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetInfoNombrePropietarioCuponResponse> GetInfoNombrePropietarioCuponAsync(string cuponCode) {
            EjemploConsumoConsola.ServiceEsteban.GetInfoNombrePropietarioCuponRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetInfoNombrePropietarioCuponRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetInfoNombrePropietarioCuponRequestBody();
            inValue.Body.cuponCode = cuponCode;
            return ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetInfoNombrePropietarioCuponAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EjemploConsumoConsola.ServiceEsteban.GetInfoCedulaPropietarioCuponResponse EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetInfoCedulaPropietarioCupon(EjemploConsumoConsola.ServiceEsteban.GetInfoCedulaPropietarioCuponRequest request) {
            return base.Channel.GetInfoCedulaPropietarioCupon(request);
        }
        
        public string GetInfoCedulaPropietarioCupon(string cuponCode) {
            EjemploConsumoConsola.ServiceEsteban.GetInfoCedulaPropietarioCuponRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetInfoCedulaPropietarioCuponRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetInfoCedulaPropietarioCuponRequestBody();
            inValue.Body.cuponCode = cuponCode;
            EjemploConsumoConsola.ServiceEsteban.GetInfoCedulaPropietarioCuponResponse retVal = ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetInfoCedulaPropietarioCupon(inValue);
            return retVal.Body.GetInfoCedulaPropietarioCuponResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetInfoCedulaPropietarioCuponResponse> EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetInfoCedulaPropietarioCuponAsync(EjemploConsumoConsola.ServiceEsteban.GetInfoCedulaPropietarioCuponRequest request) {
            return base.Channel.GetInfoCedulaPropietarioCuponAsync(request);
        }
        
        public System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetInfoCedulaPropietarioCuponResponse> GetInfoCedulaPropietarioCuponAsync(string cuponCode) {
            EjemploConsumoConsola.ServiceEsteban.GetInfoCedulaPropietarioCuponRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetInfoCedulaPropietarioCuponRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetInfoCedulaPropietarioCuponRequestBody();
            inValue.Body.cuponCode = cuponCode;
            return ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetInfoCedulaPropietarioCuponAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EjemploConsumoConsola.ServiceEsteban.GetInfoCuponActivoResponse EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetInfoCuponActivo(EjemploConsumoConsola.ServiceEsteban.GetInfoCuponActivoRequest request) {
            return base.Channel.GetInfoCuponActivo(request);
        }
        
        public string GetInfoCuponActivo(string cuponCode) {
            EjemploConsumoConsola.ServiceEsteban.GetInfoCuponActivoRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetInfoCuponActivoRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetInfoCuponActivoRequestBody();
            inValue.Body.cuponCode = cuponCode;
            EjemploConsumoConsola.ServiceEsteban.GetInfoCuponActivoResponse retVal = ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetInfoCuponActivo(inValue);
            return retVal.Body.GetInfoCuponActivoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetInfoCuponActivoResponse> EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetInfoCuponActivoAsync(EjemploConsumoConsola.ServiceEsteban.GetInfoCuponActivoRequest request) {
            return base.Channel.GetInfoCuponActivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetInfoCuponActivoResponse> GetInfoCuponActivoAsync(string cuponCode) {
            EjemploConsumoConsola.ServiceEsteban.GetInfoCuponActivoRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetInfoCuponActivoRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetInfoCuponActivoRequestBody();
            inValue.Body.cuponCode = cuponCode;
            return ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetInfoCuponActivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EjemploConsumoConsola.ServiceEsteban.GetInfoFechaCaducidadCuponResponse EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetInfoFechaCaducidadCupon(EjemploConsumoConsola.ServiceEsteban.GetInfoFechaCaducidadCuponRequest request) {
            return base.Channel.GetInfoFechaCaducidadCupon(request);
        }
        
        public string GetInfoFechaCaducidadCupon(string cuponCode) {
            EjemploConsumoConsola.ServiceEsteban.GetInfoFechaCaducidadCuponRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetInfoFechaCaducidadCuponRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetInfoFechaCaducidadCuponRequestBody();
            inValue.Body.cuponCode = cuponCode;
            EjemploConsumoConsola.ServiceEsteban.GetInfoFechaCaducidadCuponResponse retVal = ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetInfoFechaCaducidadCupon(inValue);
            return retVal.Body.GetInfoFechaCaducidadCuponResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetInfoFechaCaducidadCuponResponse> EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetInfoFechaCaducidadCuponAsync(EjemploConsumoConsola.ServiceEsteban.GetInfoFechaCaducidadCuponRequest request) {
            return base.Channel.GetInfoFechaCaducidadCuponAsync(request);
        }
        
        public System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetInfoFechaCaducidadCuponResponse> GetInfoFechaCaducidadCuponAsync(string cuponCode) {
            EjemploConsumoConsola.ServiceEsteban.GetInfoFechaCaducidadCuponRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetInfoFechaCaducidadCuponRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetInfoFechaCaducidadCuponRequestBody();
            inValue.Body.cuponCode = cuponCode;
            return ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetInfoFechaCaducidadCuponAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EjemploConsumoConsola.ServiceEsteban.GetInfoNroAplicadoCuponResponse EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetInfoNroAplicadoCupon(EjemploConsumoConsola.ServiceEsteban.GetInfoNroAplicadoCuponRequest request) {
            return base.Channel.GetInfoNroAplicadoCupon(request);
        }
        
        public string GetInfoNroAplicadoCupon(string cuponCode) {
            EjemploConsumoConsola.ServiceEsteban.GetInfoNroAplicadoCuponRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetInfoNroAplicadoCuponRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetInfoNroAplicadoCuponRequestBody();
            inValue.Body.cuponCode = cuponCode;
            EjemploConsumoConsola.ServiceEsteban.GetInfoNroAplicadoCuponResponse retVal = ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetInfoNroAplicadoCupon(inValue);
            return retVal.Body.GetInfoNroAplicadoCuponResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetInfoNroAplicadoCuponResponse> EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetInfoNroAplicadoCuponAsync(EjemploConsumoConsola.ServiceEsteban.GetInfoNroAplicadoCuponRequest request) {
            return base.Channel.GetInfoNroAplicadoCuponAsync(request);
        }
        
        public System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetInfoNroAplicadoCuponResponse> GetInfoNroAplicadoCuponAsync(string cuponCode) {
            EjemploConsumoConsola.ServiceEsteban.GetInfoNroAplicadoCuponRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetInfoNroAplicadoCuponRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetInfoNroAplicadoCuponRequestBody();
            inValue.Body.cuponCode = cuponCode;
            return ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetInfoNroAplicadoCuponAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EjemploConsumoConsola.ServiceEsteban.GetInfoCodPromoCuponResponse EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetInfoCodPromoCupon(EjemploConsumoConsola.ServiceEsteban.GetInfoCodPromoCuponRequest request) {
            return base.Channel.GetInfoCodPromoCupon(request);
        }
        
        public string GetInfoCodPromoCupon(string cuponCode) {
            EjemploConsumoConsola.ServiceEsteban.GetInfoCodPromoCuponRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetInfoCodPromoCuponRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetInfoCodPromoCuponRequestBody();
            inValue.Body.cuponCode = cuponCode;
            EjemploConsumoConsola.ServiceEsteban.GetInfoCodPromoCuponResponse retVal = ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetInfoCodPromoCupon(inValue);
            return retVal.Body.GetInfoCodPromoCuponResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetInfoCodPromoCuponResponse> EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetInfoCodPromoCuponAsync(EjemploConsumoConsola.ServiceEsteban.GetInfoCodPromoCuponRequest request) {
            return base.Channel.GetInfoCodPromoCuponAsync(request);
        }
        
        public System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetInfoCodPromoCuponResponse> GetInfoCodPromoCuponAsync(string cuponCode) {
            EjemploConsumoConsola.ServiceEsteban.GetInfoCodPromoCuponRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetInfoCodPromoCuponRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetInfoCodPromoCuponRequestBody();
            inValue.Body.cuponCode = cuponCode;
            return ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetInfoCodPromoCuponAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EjemploConsumoConsola.ServiceEsteban.GetInfoTipoPromoCuponResponse EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetInfoTipoPromoCupon(EjemploConsumoConsola.ServiceEsteban.GetInfoTipoPromoCuponRequest request) {
            return base.Channel.GetInfoTipoPromoCupon(request);
        }
        
        public string GetInfoTipoPromoCupon(string cuponCode) {
            EjemploConsumoConsola.ServiceEsteban.GetInfoTipoPromoCuponRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetInfoTipoPromoCuponRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetInfoTipoPromoCuponRequestBody();
            inValue.Body.cuponCode = cuponCode;
            EjemploConsumoConsola.ServiceEsteban.GetInfoTipoPromoCuponResponse retVal = ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetInfoTipoPromoCupon(inValue);
            return retVal.Body.GetInfoTipoPromoCuponResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetInfoTipoPromoCuponResponse> EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetInfoTipoPromoCuponAsync(EjemploConsumoConsola.ServiceEsteban.GetInfoTipoPromoCuponRequest request) {
            return base.Channel.GetInfoTipoPromoCuponAsync(request);
        }
        
        public System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetInfoTipoPromoCuponResponse> GetInfoTipoPromoCuponAsync(string cuponCode) {
            EjemploConsumoConsola.ServiceEsteban.GetInfoTipoPromoCuponRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetInfoTipoPromoCuponRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetInfoTipoPromoCuponRequestBody();
            inValue.Body.cuponCode = cuponCode;
            return ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetInfoTipoPromoCuponAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EjemploConsumoConsola.ServiceEsteban.GetTipoPromocionCamposlibresResponse EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetTipoPromocionCamposlibres(EjemploConsumoConsola.ServiceEsteban.GetTipoPromocionCamposlibresRequest request) {
            return base.Channel.GetTipoPromocionCamposlibres(request);
        }
        
        public string GetTipoPromocionCamposlibres(string codPromocion) {
            EjemploConsumoConsola.ServiceEsteban.GetTipoPromocionCamposlibresRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetTipoPromocionCamposlibresRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetTipoPromocionCamposlibresRequestBody();
            inValue.Body.codPromocion = codPromocion;
            EjemploConsumoConsola.ServiceEsteban.GetTipoPromocionCamposlibresResponse retVal = ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetTipoPromocionCamposlibres(inValue);
            return retVal.Body.GetTipoPromocionCamposlibresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetTipoPromocionCamposlibresResponse> EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetTipoPromocionCamposlibresAsync(EjemploConsumoConsola.ServiceEsteban.GetTipoPromocionCamposlibresRequest request) {
            return base.Channel.GetTipoPromocionCamposlibresAsync(request);
        }
        
        public System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetTipoPromocionCamposlibresResponse> GetTipoPromocionCamposlibresAsync(string codPromocion) {
            EjemploConsumoConsola.ServiceEsteban.GetTipoPromocionCamposlibresRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetTipoPromocionCamposlibresRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetTipoPromocionCamposlibresRequestBody();
            inValue.Body.codPromocion = codPromocion;
            return ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetTipoPromocionCamposlibresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EjemploConsumoConsola.ServiceEsteban.GetCodArticuloPromoResponse EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetCodArticuloPromo(EjemploConsumoConsola.ServiceEsteban.GetCodArticuloPromoRequest request) {
            return base.Channel.GetCodArticuloPromo(request);
        }
        
        public string GetCodArticuloPromo(string cuponCode) {
            EjemploConsumoConsola.ServiceEsteban.GetCodArticuloPromoRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetCodArticuloPromoRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetCodArticuloPromoRequestBody();
            inValue.Body.cuponCode = cuponCode;
            EjemploConsumoConsola.ServiceEsteban.GetCodArticuloPromoResponse retVal = ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetCodArticuloPromo(inValue);
            return retVal.Body.GetCodArticuloPromoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetCodArticuloPromoResponse> EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetCodArticuloPromoAsync(EjemploConsumoConsola.ServiceEsteban.GetCodArticuloPromoRequest request) {
            return base.Channel.GetCodArticuloPromoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetCodArticuloPromoResponse> GetCodArticuloPromoAsync(string cuponCode) {
            EjemploConsumoConsola.ServiceEsteban.GetCodArticuloPromoRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetCodArticuloPromoRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetCodArticuloPromoRequestBody();
            inValue.Body.cuponCode = cuponCode;
            return ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetCodArticuloPromoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EjemploConsumoConsola.ServiceEsteban.GetUnidadesRegaloPromoResponse EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetUnidadesRegaloPromo(EjemploConsumoConsola.ServiceEsteban.GetUnidadesRegaloPromoRequest request) {
            return base.Channel.GetUnidadesRegaloPromo(request);
        }
        
        public string GetUnidadesRegaloPromo(string cuponCode) {
            EjemploConsumoConsola.ServiceEsteban.GetUnidadesRegaloPromoRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetUnidadesRegaloPromoRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetUnidadesRegaloPromoRequestBody();
            inValue.Body.cuponCode = cuponCode;
            EjemploConsumoConsola.ServiceEsteban.GetUnidadesRegaloPromoResponse retVal = ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetUnidadesRegaloPromo(inValue);
            return retVal.Body.GetUnidadesRegaloPromoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetUnidadesRegaloPromoResponse> EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetUnidadesRegaloPromoAsync(EjemploConsumoConsola.ServiceEsteban.GetUnidadesRegaloPromoRequest request) {
            return base.Channel.GetUnidadesRegaloPromoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetUnidadesRegaloPromoResponse> GetUnidadesRegaloPromoAsync(string cuponCode) {
            EjemploConsumoConsola.ServiceEsteban.GetUnidadesRegaloPromoRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetUnidadesRegaloPromoRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetUnidadesRegaloPromoRequestBody();
            inValue.Body.cuponCode = cuponCode;
            return ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetUnidadesRegaloPromoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EjemploConsumoConsola.ServiceEsteban.GetDescuentoPromoResponse EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetDescuentoPromo(EjemploConsumoConsola.ServiceEsteban.GetDescuentoPromoRequest request) {
            return base.Channel.GetDescuentoPromo(request);
        }
        
        public string GetDescuentoPromo(string cuponCode) {
            EjemploConsumoConsola.ServiceEsteban.GetDescuentoPromoRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetDescuentoPromoRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetDescuentoPromoRequestBody();
            inValue.Body.cuponCode = cuponCode;
            EjemploConsumoConsola.ServiceEsteban.GetDescuentoPromoResponse retVal = ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetDescuentoPromo(inValue);
            return retVal.Body.GetDescuentoPromoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetDescuentoPromoResponse> EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetDescuentoPromoAsync(EjemploConsumoConsola.ServiceEsteban.GetDescuentoPromoRequest request) {
            return base.Channel.GetDescuentoPromoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetDescuentoPromoResponse> GetDescuentoPromoAsync(string cuponCode) {
            EjemploConsumoConsola.ServiceEsteban.GetDescuentoPromoRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetDescuentoPromoRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetDescuentoPromoRequestBody();
            inValue.Body.cuponCode = cuponCode;
            return ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetDescuentoPromoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EjemploConsumoConsola.ServiceEsteban.GetDesImportePromoResponse EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetDesImportePromo(EjemploConsumoConsola.ServiceEsteban.GetDesImportePromoRequest request) {
            return base.Channel.GetDesImportePromo(request);
        }
        
        public string GetDesImportePromo(string cuponCode) {
            EjemploConsumoConsola.ServiceEsteban.GetDesImportePromoRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetDesImportePromoRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetDesImportePromoRequestBody();
            inValue.Body.cuponCode = cuponCode;
            EjemploConsumoConsola.ServiceEsteban.GetDesImportePromoResponse retVal = ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetDesImportePromo(inValue);
            return retVal.Body.GetDesImportePromoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetDesImportePromoResponse> EjemploConsumoConsola.ServiceEsteban.Service1Soap.GetDesImportePromoAsync(EjemploConsumoConsola.ServiceEsteban.GetDesImportePromoRequest request) {
            return base.Channel.GetDesImportePromoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EjemploConsumoConsola.ServiceEsteban.GetDesImportePromoResponse> GetDesImportePromoAsync(string cuponCode) {
            EjemploConsumoConsola.ServiceEsteban.GetDesImportePromoRequest inValue = new EjemploConsumoConsola.ServiceEsteban.GetDesImportePromoRequest();
            inValue.Body = new EjemploConsumoConsola.ServiceEsteban.GetDesImportePromoRequestBody();
            inValue.Body.cuponCode = cuponCode;
            return ((EjemploConsumoConsola.ServiceEsteban.Service1Soap)(this)).GetDesImportePromoAsync(inValue);
        }
    }
}
