//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirServicioWeb.EjemploAsmx {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonaDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PersonaDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        private System.DateTime FechaNacimientoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EjemploAsmx.EjemploAsmxSoap")]
    public interface EjemploAsmxSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ConsumirServicioWeb.EjemploAsmx.HelloWorldResponse HelloWorld(ConsumirServicioWeb.EjemploAsmx.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirServicioWeb.EjemploAsmx.HelloWorldResponse> HelloWorldAsync(ConsumirServicioWeb.EjemploAsmx.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularMayor", ReplyAction="*")]
        int CalcularMayor(int valor1, int valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularMayor", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CalcularMayorAsync(int valor1, int valor2);
        
        // CODEGEN: Generating message contract since element name SelectAllPersonasResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllPersonas", ReplyAction="*")]
        ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasResponse SelectAllPersonas(ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllPersonas", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasResponse> SelectAllPersonasAsync(ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (SelectAllPersonasAdd) of message SelectAllPersonasAdd does not match the default value (SelectAllPersonas1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllPersonasAdd", ReplyAction="*")]
        ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasAdd1 SelectAllPersonas1(ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasAdd request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllPersonasAdd", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasAdd1> SelectAllPersonas1Async(ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasAdd request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirServicioWeb.EjemploAsmx.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsumirServicioWeb.EjemploAsmx.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirServicioWeb.EjemploAsmx.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsumirServicioWeb.EjemploAsmx.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllPersonasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllPersonas", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasRequestBody Body;
        
        public SelectAllPersonasRequest() {
        }
        
        public SelectAllPersonasRequest(ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectAllPersonasRequestBody {
        
        public SelectAllPersonasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllPersonasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllPersonasResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasResponseBody Body;
        
        public SelectAllPersonasResponse() {
        }
        
        public SelectAllPersonasResponse(ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAllPersonasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ConsumirServicioWeb.EjemploAsmx.PersonaDto> SelectAllPersonasResult;
        
        public SelectAllPersonasResponseBody() {
        }
        
        public SelectAllPersonasResponseBody(System.Collections.Generic.List<ConsumirServicioWeb.EjemploAsmx.PersonaDto> SelectAllPersonasResult) {
            this.SelectAllPersonasResult = SelectAllPersonasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectAllPersonasAdd", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectAllPersonasAdd {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ConsumirServicioWeb.EjemploAsmx.PersonaDto personaDto;
        
        public SelectAllPersonasAdd() {
        }
        
        public SelectAllPersonasAdd(ConsumirServicioWeb.EjemploAsmx.PersonaDto personaDto) {
            this.personaDto = personaDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectAllPersonasAddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectAllPersonasAdd1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ConsumirServicioWeb.EjemploAsmx.PersonaDto> SelectAllPersonasAddResult;
        
        public SelectAllPersonasAdd1() {
        }
        
        public SelectAllPersonasAdd1(System.Collections.Generic.List<ConsumirServicioWeb.EjemploAsmx.PersonaDto> SelectAllPersonasAddResult) {
            this.SelectAllPersonasAddResult = SelectAllPersonasAddResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EjemploAsmxSoapChannel : ConsumirServicioWeb.EjemploAsmx.EjemploAsmxSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EjemploAsmxSoapClient : System.ServiceModel.ClientBase<ConsumirServicioWeb.EjemploAsmx.EjemploAsmxSoap>, ConsumirServicioWeb.EjemploAsmx.EjemploAsmxSoap {
        
        public EjemploAsmxSoapClient() {
        }
        
        public EjemploAsmxSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EjemploAsmxSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EjemploAsmxSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EjemploAsmxSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirServicioWeb.EjemploAsmx.HelloWorldResponse ConsumirServicioWeb.EjemploAsmx.EjemploAsmxSoap.HelloWorld(ConsumirServicioWeb.EjemploAsmx.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsumirServicioWeb.EjemploAsmx.HelloWorldRequest inValue = new ConsumirServicioWeb.EjemploAsmx.HelloWorldRequest();
            inValue.Body = new ConsumirServicioWeb.EjemploAsmx.HelloWorldRequestBody();
            ConsumirServicioWeb.EjemploAsmx.HelloWorldResponse retVal = ((ConsumirServicioWeb.EjemploAsmx.EjemploAsmxSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirServicioWeb.EjemploAsmx.HelloWorldResponse> ConsumirServicioWeb.EjemploAsmx.EjemploAsmxSoap.HelloWorldAsync(ConsumirServicioWeb.EjemploAsmx.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirServicioWeb.EjemploAsmx.HelloWorldResponse> HelloWorldAsync() {
            ConsumirServicioWeb.EjemploAsmx.HelloWorldRequest inValue = new ConsumirServicioWeb.EjemploAsmx.HelloWorldRequest();
            inValue.Body = new ConsumirServicioWeb.EjemploAsmx.HelloWorldRequestBody();
            return ((ConsumirServicioWeb.EjemploAsmx.EjemploAsmxSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int CalcularMayor(int valor1, int valor2) {
            return base.Channel.CalcularMayor(valor1, valor2);
        }
        
        public System.Threading.Tasks.Task<int> CalcularMayorAsync(int valor1, int valor2) {
            return base.Channel.CalcularMayorAsync(valor1, valor2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasResponse ConsumirServicioWeb.EjemploAsmx.EjemploAsmxSoap.SelectAllPersonas(ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasRequest request) {
            return base.Channel.SelectAllPersonas(request);
        }
        
        public System.Collections.Generic.List<ConsumirServicioWeb.EjemploAsmx.PersonaDto> SelectAllPersonas() {
            ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasRequest inValue = new ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasRequest();
            inValue.Body = new ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasRequestBody();
            ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasResponse retVal = ((ConsumirServicioWeb.EjemploAsmx.EjemploAsmxSoap)(this)).SelectAllPersonas(inValue);
            return retVal.Body.SelectAllPersonasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasResponse> ConsumirServicioWeb.EjemploAsmx.EjemploAsmxSoap.SelectAllPersonasAsync(ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasRequest request) {
            return base.Channel.SelectAllPersonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasResponse> SelectAllPersonasAsync() {
            ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasRequest inValue = new ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasRequest();
            inValue.Body = new ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasRequestBody();
            return ((ConsumirServicioWeb.EjemploAsmx.EjemploAsmxSoap)(this)).SelectAllPersonasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasAdd1 ConsumirServicioWeb.EjemploAsmx.EjemploAsmxSoap.SelectAllPersonas1(ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasAdd request) {
            return base.Channel.SelectAllPersonas1(request);
        }
        
        public System.Collections.Generic.List<ConsumirServicioWeb.EjemploAsmx.PersonaDto> SelectAllPersonas1(ConsumirServicioWeb.EjemploAsmx.PersonaDto personaDto) {
            ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasAdd inValue = new ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasAdd();
            inValue.personaDto = personaDto;
            ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasAdd1 retVal = ((ConsumirServicioWeb.EjemploAsmx.EjemploAsmxSoap)(this)).SelectAllPersonas1(inValue);
            return retVal.SelectAllPersonasAddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasAdd1> ConsumirServicioWeb.EjemploAsmx.EjemploAsmxSoap.SelectAllPersonas1Async(ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasAdd request) {
            return base.Channel.SelectAllPersonas1Async(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasAdd1> SelectAllPersonas1Async(ConsumirServicioWeb.EjemploAsmx.PersonaDto personaDto) {
            ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasAdd inValue = new ConsumirServicioWeb.EjemploAsmx.SelectAllPersonasAdd();
            inValue.personaDto = personaDto;
            return ((ConsumirServicioWeb.EjemploAsmx.EjemploAsmxSoap)(this)).SelectAllPersonas1Async(inValue);
        }
    }
}
