//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cedesistemas.Model.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudades
    {
        public Ciudades()
        {
            this.Hoteles = new HashSet<Hoteles>();
            this.Vuelos = new HashSet<Vuelos>();
            this.Vuelos1 = new HashSet<Vuelos>();
        }
    
        public int CiudadId { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> DepartamentoId { get; set; }
    
        public virtual ICollection<Hoteles> Hoteles { get; set; }
        public virtual ICollection<Vuelos> Vuelos { get; set; }
        public virtual ICollection<Vuelos> Vuelos1 { get; set; }
        public virtual Departamentos Departamentos { get; set; }
    }
}
