//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cedesistemas.Model.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoteles
    {
        public Hoteles()
        {
            this.Servicios = new HashSet<Servicios>();
        }
    
        public int HotelId { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> NumeroPlazas { get; set; }
        public int CadenaId { get; set; }
        public Nullable<int> CiudadId { get; set; }
    
        public virtual Cadenas Cadenas { get; set; }
        public virtual Ciudades Ciudades { get; set; }
        public virtual ICollection<Servicios> Servicios { get; set; }
    }
}
