//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cedesistemas.Model.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimientos
    {
        public int MovimientoId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> ServicioId { get; set; }
        public Nullable<int> VueloId { get; set; }
        public Nullable<System.DateTime> FechaLlegada { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public string ClaseVuelo { get; set; }
        public string CodigoReserva { get; set; }
        public int AgenciaId { get; set; }
    
        public virtual Agencias Agencias { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Servicios Servicios { get; set; }
        public virtual Vuelos Vuelos { get; set; }
    }
}
