//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cedesistemas.Model.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios
    {
        public Servicios()
        {
            this.Movimientos = new HashSet<Movimientos>();
        }
    
        public int ServicioId { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<bool> Activo { get; set; }
        public int HotelId { get; set; }
        public int Descuento { get; set; }
    
        public virtual Hoteles Hoteles { get; set; }
        public virtual ICollection<Movimientos> Movimientos { get; set; }
    }
}
