//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cedesistemas.Model.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelos
    {
        public Vuelos()
        {
            this.Movimientos = new HashSet<Movimientos>();
        }
    
        public int VueloId { get; set; }
        public string Codigo { get; set; }
        public System.DateTime FechaVuelo { get; set; }
        public System.TimeSpan HoraVuelo { get; set; }
        public int CiudadIdOrigen { get; set; }
        public int CiudadIdDestino { get; set; }
        public Nullable<int> NumeroPlazaEjecutiva { get; set; }
        public Nullable<int> NumeroPlazaTurista { get; set; }
        public int CadenaId { get; set; }
    
        public virtual Cadenas Cadenas { get; set; }
        public virtual Ciudades Ciudades { get; set; }
        public virtual Ciudades Ciudades1 { get; set; }
        public virtual ICollection<Movimientos> Movimientos { get; set; }
    }
}
